### ISSUE TITLE
Error on Mongo DB and then Failed to get adb devices from code , but from command line I able to see the devices.

### ISSUE THREAD

**Issue by asitishere** [testvagrant/optimusTemplate#12]
13:46:35.787 [ERROR] [system.err] 108 [main] INFO org.mongodb.driver.cluster - No server chosen by ReadPreferenceServerSelector{readPreference=primary} from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, serverDescriptions=[ServerDescription{address=localhost:27017, type=UNKNOWN, state=CONNECTING}]}. Waiting for 30000 ms before timing out
13:46:35.791 [ERROR] [system.err] 112 [cluster-ClusterId{value='59ed580b17235e08d4dc7719', description='null'}-localhost:27017] INFO org.mongodb.driver.connection - Opened connection [connectionId{localValue:1, serverValue:29}] to localhost:27017
13:46:35.792 [ERROR] [system.err] 113 [cluster-ClusterId{value='59ed580b17235e08d4dc7719', description='null'}-localhost:27017] INFO org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 4, 9]}, minWireVersion=0, maxWireVersion=5, maxDocumentSize=16777216, roundTripTimeNanos=450948}
13:46:35.797 [ERROR] [system.err] 118 [main] INFO org.mongodb.driver.connection - Opened connection [connectionId{localValue:2, serverValue:30}] to localhost:27017
13:46:35.822 [QUIET] [system.out] -------- All devices and there status --------
13:46:35.822 [QUIET] [system.out] CB5A28GAZP --- Available
13:46:35.827 [QUIET] [system.out] MongoClient:1648458262
13:46:35.827 [QUIET] [system.out] Updating first available device to Engaged
13:46:35.838 [QUIET] [system.out] Device query -- { "$and" : [ { "status" : "Available"} , { "platform" : "ANDROID"} , { "udid" : "CB5A28GAZP"}] , "buildId" : { "$oid" : "59ed58051a43d90828c1d4ed"}}
13:46:35.860 [QUIET] [system.out] Updated device E5823 to engaged
13:46:35.862 [QUIET] [system.out] Scenario id -- say-hello-to-optimus;hello-optimus
13:46:35.862 [QUIET] [system.out] Scenario Name -- Hello Optimus
13:46:35.863 [QUIET] [system.out] Failure in before hook:StartingSteps.setUp(Scenario)
13:46:35.863 [QUIET] [system.out] Message: java.lang.RuntimeException: Cannot extract line number from the String.say-hello-to-optimus;hello-optimus
13:46:35.863 [QUIET] [system.out]       at com.testvagrant.commons.helpers.ScenarioHelper.getLineNumber(ScenarioHelper.java:71)
13:46:35.863 [QUIET] [system.out]       at com.testvagrant.commons.helpers.ScenarioHelper.getUniqueScenarioName(ScenarioHelper.java:42)
13:46:35.863 [QUIET] [system.out]       at com.testvagrant.optimus.device.OptimusController.registerSmartBOTs(OptimusController.java:156)
13:46:35.863 [QUIET] [system.out]       at steps.StartingSteps.setUp(StartingSteps.java:20)
13:46:35.863 [QUIET] [system.out]       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:46:35.863 [QUIET] [system.out]       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:46:35.863 [QUIET] [system.out]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:46:35.863 [QUIET] [system.out]       at java.lang.reflect.Method.invoke(Method.java:498)
13:46:35.863 [QUIET] [system.out]       at cucumber.runtime.Utils$1.call(Utils.java:40)
13:46:35.863 [QUIET] [system.out]       at cucumber.runtime.Timeout.timeout(Timeout.java:16)
13:46:35.863 [QUIET] [system.out]       at cucumber.runtime.Utils.invoke(Utils.java:34)
13:46:35.863 [QUIET] [system.out]       at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
13:46:35.864 [QUIET] [system.out]       at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:224)
13:46:35.864 [QUIET] [system.out]       at cucumber.runtime.Runtime.runHooks(Runtime.java:212)
13:46:35.864 [QUIET] [system.out]       at cucumber.runtime.Runtime.runBeforeHooks(Runtime.java:202)
13:46:35.864 [QUIET] [system.out]       at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:40)
13:46:35.864 [QUIET] [system.out]       at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
13:46:35.864 [QUIET] [system.out]       at cucumber.runtime.Runtime.run(Runtime.java:122)
13:46:35.864 [QUIET] [system.out]       at cucumber.api.cli.Main.run(Main.java:36)
13:46:35.864 [QUIET] [system.out]       at cucumber.api.cli.Main.main(Main.java:18)
13:46:35.864 [QUIET] [system.out] 
13:46:35.864 [QUIET] [system.out]       java.lang.RuntimeException: Cannot extract line number from the String.say-hello-to-optimus;hello-optimus
13:46:35.864 [QUIET] [system.out]               at com.testvagrant.commons.helpers.ScenarioHelper.getLineNumber(ScenarioHelper.java:71)
13:46:35.864 [QUIET] [system.out]               at com.testvagrant.commons.helpers.ScenarioHelper.getUniqueScenarioName(ScenarioHelper.java:42)
13:46:35.864 [QUIET] [system.out]               at com.testvagrant.optimus.device.OptimusController.registerSmartBOTs(OptimusController.java:156)
13:46:35.864 [QUIET] [system.out]               at steps.StartingSteps.setUp(StartingSteps.java:20)
13:46:35.864 [QUIET] [system.out]               at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:46:35.864 [QUIET] [system.out]               at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:46:35.864 [QUIET] [system.out]               at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:46:35.864 [QUIET] [system.out]               at java.lang.reflect.Method.invoke(Method.java:498)
13:46:35.864 [QUIET] [system.out]               at cucumber.runtime.Utils$1.call(Utils.java:40)
13:46:35.864 [QUIET] [system.out]               at cucumber.runtime.Timeout.timeout(Timeout.java:16)
13:46:35.864 [QUIET] [system.out]               at cucumber.runtime.Utils.invoke(Utils.java:34)
13:46:35.864 [QUIET] [system.out]               at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
13:46:35.864 [QUIET] [system.out]               at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:224)
13:46:35.864 [QUIET] [system.out]               at cucumber.runtime.Runtime.runHooks(Runtime.java:212)
13:46:35.864 [QUIET] [system.out]               at cucumber.runtime.Runtime.runBeforeHooks(Runtime.java:202)
13:46:35.864 [QUIET] [system.out]               at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:40)
13:46:35.864 [QUIET] [system.out]               at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
13:46:35.864 [QUIET] [system.out]               at cucumber.runtime.Runtime.run(Runtime.java:122)
13:46:35.864 [QUIET] [system.out]               at cucumber.api.cli.Main.run(Main.java:36)
13:46:35.864 [QUIET] [system.out]               at cucumber.api.cli.Main.main(Main.java:18)
13:46:35.865 [QUIET] [system.out]       
13:46:35.868 [QUIET] [system.out] Failure in after hook:StartingSteps.tearDown(Scenario)
13:46:35.868 [QUIET] [system.out] Message: java.lang.NullPointerException
13:46:35.868 [QUIET] [system.out]       at steps.StartingSteps.tearDown(StartingSteps.java:29)
13:46:35.868 [QUIET] [system.out]       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:46:35.868 [QUIET] [system.out]       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:46:35.868 [QUIET] [system.out]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:46:35.868 [QUIET] [system.out]       at java.lang.reflect.Method.invoke(Method.java:498)
13:46:35.868 [QUIET] [system.out]       at cucumber.runtime.Utils$1.call(Utils.java:40)
13:46:35.868 [QUIET] [system.out]       at cucumber.runtime.Timeout.timeout(Timeout.java:16)
13:46:35.868 [QUIET] [system.out]       at cucumber.runtime.Utils.invoke(Utils.java:34)
13:46:35.868 [QUIET] [system.out]       at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
13:46:35.868 [QUIET] [system.out]       at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:224)
13:46:35.868 [QUIET] [system.out]       at cucumber.runtime.Runtime.runHooks(Runtime.java:212)
13:46:35.868 [QUIET] [system.out]       at cucumber.runtime.Runtime.runAfterHooks(Runtime.java:206)
13:46:35.869 [QUIET] [system.out]       at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:46)
13:46:35.869 [QUIET] [system.out]       at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
13:46:35.869 [QUIET] [system.out]       at cucumber.runtime.Runtime.run(Runtime.java:122)
13:46:35.869 [QUIET] [system.out]       at cucumber.api.cli.Main.run(Main.java:36)
13:46:35.869 [QUIET] [system.out]       at cucumber.api.cli.Main.main(Main.java:18)
13:46:35.869 [QUIET] [system.out] 
13:46:35.869 [QUIET] [system.out]       java.lang.NullPointerException
13:46:35.869 [QUIET] [system.out]               at steps.StartingSteps.tearDown(StartingSteps.java:29)
13:46:35.869 [QUIET] [system.out]               at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:46:35.869 [QUIET] [system.out]               at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:46:35.869 [QUIET] [system.out]               at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:46:35.869 [QUIET] [system.out]               at java.lang.reflect.Method.invoke(Method.java:498)
13:46:35.869 [QUIET] [system.out]               at cucumber.runtime.Utils$1.call(Utils.java:40)
13:46:35.869 [QUIET] [system.out]               at cucumber.runtime.Timeout.timeout(Timeout.java:16)
13:46:35.869 [QUIET] [system.out]               at cucumber.runtime.Utils.invoke(Utils.java:34)
13:46:35.869 [QUIET] [system.out]               at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
13:46:35.869 [QUIET] [system.out]               at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:224)
13:46:35.869 [QUIET] [system.out]               at cucumber.runtime.Runtime.runHooks(Runtime.java:212)
13:46:35.869 [QUIET] [system.out]               at cucumber.runtime.Runtime.runAfterHooks(Runtime.java:206)
13:46:35.869 [QUIET] [system.out]               at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:46)
13:46:35.869 [QUIET] [system.out]               at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
13:46:35.869 [QUIET] [system.out]               at cucumber.runtime.Runtime.run(Runtime.java:122)
13:46:35.869 [QUIET] [system.out]               at cucumber.api.cli.Main.run(Main.java:36)
13:46:35.869 [QUIET] [system.out]               at cucumber.api.cli.Main.main(Main.java:18)
13:46:35.869 [QUIET] [system.out]       
13:46:35.869 [QUIET] [system.out] 
13:46:35.869 [QUIET] [system.out]   @helloOptimus
13:46:35.869 [QUIET] [system.out]   Scenario: Hello Optimus                                                  # HelloOptimus.feature:4
13:46:35.870 [QUIET] [system.out]     Given I have optimus hello application                                 # HelloOptimusSteps.iHaveOptimusHelloApplication()
13:46:35.870 [QUIET] [system.out]     When I open it on either emulator, simulator or device on any platform # HelloOptimusSteps.iOpenItOnEitherEmulatorSimulatorOrDeviceOnAnyPlatform()
13:46:35.870 [QUIET] [system.out]     Then I should be able to say a hello to optimus                        # HelloOptimusSteps.iShouldBeAbleToSayAHelloToOptimus()
13:46:35.870 [QUIET] [system.out] Feature: Say Hello to Optimus
13:46:35.870 [QUIET] [system.out]   Using generic steps, I want read the welcome message
13:46:35.870 [QUIET] [system.out] appJson updated with - CB5A28GAZP
13:46:35.870 [QUIET] [system.out] {"executionDetails":{"appium_js_path":"/usr/local/bin/appium","monitoring":true,"appium_node_path":"/usr/local/bin/node"},"testFeed":[{"optimusDesiredCapabilities":{"appiumServerCapabilities":{"app":"HelloOptimus.apk","platformName":"Android","udid":"CB5A28GAZP"},"androidOnlyCapabilities":{"appActivity":"com.testvagrant.hellooptimus.MainActivity","appPackage":"com.testvagrant.hellooptimus","avdLaunchTimeout":300000,"useKeystore":false}},"appDir":"app","runsOn":"any","deviceState":{"captureVideo":true},"belongsTo":"optimus","nativeApp":true}]}
13:46:35.871 [QUIET] [system.out] 2017-10-23 13:46:35 INFO  OptimusController:147 - Starting Scenario -- generic step example
13:46:35.871 [QUIET] [system.out] updated testFeed -- {"optimusDesiredCapabilities":{"appiumServerCapabilities":{"app":"HelloOptimus.apk","platformName":"Android","udid":"CB5A28GAZP"},"androidOnlyCapabilities":{"appActivity":"com.testvagrant.hellooptimus.MainActivity","appPackage":"com.testvagrant.hellooptimus","avdLaunchTimeout":300000,"useKeystore":false}},"appDir":"app","runsOn":"any","deviceState":{"captureVideo":true},"belongsTo":"optimus","nativeApp":true}
13:46:35.871 [QUIET] [system.out] MongoClient:1648458262
13:46:35.873 [QUIET] [system.out] -------- All devices and there status --------
13:46:35.873 [QUIET] [system.out] CB5A28GAZP --- Engaged
13:46:35.873 [QUIET] [system.out] MongoClient:1648458262
13:46:35.873 [QUIET] [system.out] Updating first available device to Engaged
13:46:35.873 [QUIET] [system.out] Device query -- { "$and" : [ { "status" : "Available"} , { "platform" : "ANDROID"} , { "udid" : "CB5A28GAZP"}] , "buildId" : { "$oid" : "59ed58051a43d90828c1d4ed"}}
13:46:35.875 [QUIET] [system.out] Failure in before hook:StartingSteps.setUp(Scenario)
13:46:35.875 [QUIET] [system.out] Message: java.lang.NullPointerException: Unable to Mark Device to 'Engaged'. Check for device State using `adb devices`. If it is offline, kill the adb server `adb kill-server` and try again.
13:46:35.875 [QUIET] [system.out]       at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:799)
13:46:35.875 [QUIET] [system.out]       at com.testvagrant.monitor.radiator.MongoWriter.updateFirstAvailableDeviceToEngaged(MongoWriter.java:160)
13:46:35.875 [QUIET] [system.out]       at com.testvagrant.optimus.device.DeviceFinder.getAvailableDeviceAndUpdateToEngaged(DeviceFinder.java:56)
13:46:35.875 [QUIET] [system.out]       at com.testvagrant.optimus.parser.OptimusConfigParser.mapOwnerToDesiredCapabilities(OptimusConfigParser.java:61)
13:46:35.875 [QUIET] [system.out]       at com.testvagrant.optimus.device.OptimusController.registerSmartBOTs(OptimusController.java:151)
13:46:35.875 [QUIET] [system.out]       at steps.StartingSteps.setUp(StartingSteps.java:20)
13:46:35.875 [QUIET] [system.out]       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:46:35.875 [QUIET] [system.out]       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:46:35.875 [QUIET] [system.out]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:46:35.875 [QUIET] [system.out]       at java.lang.reflect.Method.invoke(Method.java:498)
13:46:35.875 [QUIET] [system.out]       at cucumber.runtime.Utils$1.call(Utils.java:40)
13:46:35.875 [QUIET] [system.out]       at cucumber.runtime.Timeout.timeout(Timeout.java:16)
13:46:35.875 [QUIET] [system.out]       at cucumber.runtime.Utils.invoke(Utils.java:34)
13:46:35.875 [QUIET] [system.out]       at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
13:46:35.875 [QUIET] [system.out]       at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:224)
13:46:35.875 [QUIET] [system.out]       at cucumber.runtime.Runtime.runHooks(Runtime.java:212)
13:46:35.875 [QUIET] [system.out]       at cucumber.runtime.Runtime.runBeforeHooks(Runtime.java:202)
13:46:35.875 [QUIET] [system.out]       at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:40)
13:46:35.875 [QUIET] [system.out]       at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
13:46:35.875 [QUIET] [system.out]       at cucumber.runtime.Runtime.run(Runtime.java:122)
13:46:35.876 [QUIET] [system.out]       at cucumber.api.cli.Main.run(Main.java:36)
13:46:35.876 [QUIET] [system.out]       at cucumber.api.cli.Main.main(Main.java:18)
13:46:35.876 [QUIET] [system.out] 
13:46:35.876 [QUIET] [system.out]       java.lang.NullPointerException: Unable to Mark Device to 'Engaged'. Check for device State using `adb devices`. If it is offline, kill the adb server `adb kill-server` and try again.
13:46:35.876 [QUIET] [system.out]               at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:799)
13:46:35.876 [QUIET] [system.out]               at com.testvagrant.monitor.radiator.MongoWriter.updateFirstAvailableDeviceToEngaged(MongoWriter.java:160)
13:46:35.876 [QUIET] [system.out]               at com.testvagrant.optimus.device.DeviceFinder.getAvailableDeviceAndUpdateToEngaged(DeviceFinder.java:56)
13:46:35.876 [QUIET] [system.out]               at com.testvagrant.optimus.parser.OptimusConfigParser.mapOwnerToDesiredCapabilities(OptimusConfigParser.java:61)
13:46:35.876 [QUIET] [system.out]               at com.testvagrant.optimus.device.OptimusController.registerSmartBOTs(OptimusController.java:151)
13:46:35.876 [QUIET] [system.out]               at steps.StartingSteps.setUp(StartingSteps.java:20)
13:46:35.876 [QUIET] [system.out]               at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:46:35.876 [QUIET] [system.out]               at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:46:35.876 [QUIET] [system.out]               at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:46:35.876 [QUIET] [system.out]               at java.lang.reflect.Method.invoke(Method.java:498)
13:46:35.876 [QUIET] [system.out]               at cucumber.runtime.Utils$1.call(Utils.java:40)
13:46:35.876 [QUIET] [system.out]               at cucumber.runtime.Timeout.timeout(Timeout.java:16)
13:46:35.876 [QUIET] [system.out]               at cucumber.runtime.Utils.invoke(Utils.java:34)
13:46:35.876 [QUIET] [system.out]               at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
13:46:35.876 [QUIET] [system.out]               at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:224)
13:46:35.876 [QUIET] [system.out]               at cucumber.runtime.Runtime.runHooks(Runtime.java:212)
13:46:35.876 [QUIET] [system.out]               at cucumber.runtime.Runtime.runBeforeHooks(Runtime.java:202)
13:46:35.876 [QUIET] [system.out]               at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:40)
13:46:35.876 [QUIET] [system.out]               at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
13:46:35.876 [QUIET] [system.out]               at cucumber.runtime.Runtime.run(Runtime.java:122)
13:46:35.876 [QUIET] [system.out]               at cucumber.api.cli.Main.run(Main.java:36)
13:46:35.876 [QUIET] [system.out]               at cucumber.api.cli.Main.main(Main.java:18)
13:46:35.876 [QUIET] [system.out]       
13:46:35.877 [QUIET] [system.out] Failure in after hook:StartingSteps.tearDown(Scenario)
13:46:35.877 [QUIET] [system.out] Message: java.lang.NullPointerException
13:46:35.877 [QUIET] [system.out]       at steps.StartingSteps.tearDown(StartingSteps.java:29)
13:46:35.877 [QUIET] [system.out]       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:46:35.877 [QUIET] [system.out]       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:46:35.877 [QUIET] [system.out]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:46:35.877 [QUIET] [system.out]       at java.lang.reflect.Method.invoke(Method.java:498)
13:46:35.877 [QUIET] [system.out]       at cucumber.runtime.Utils$1.call(Utils.java:40)
13:46:35.877 [QUIET] [system.out]       at cucumber.runtime.Timeout.timeout(Timeout.java:16)
13:46:35.877 [QUIET] [system.out]       at cucumber.runtime.Utils.invoke(Utils.java:34)
13:46:35.877 [QUIET] [system.out]       at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
13:46:35.877 [QUIET] [system.out]       at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:224)
13:46:35.877 [QUIET] [system.out]       at cucumber.runtime.Runtime.runHooks(Runtime.java:212)
13:46:35.877 [QUIET] [system.out]       at cucumber.runtime.Runtime.runAfterHooks(Runtime.java:206)
13:46:35.877 [QUIET] [system.out]       at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:46)
13:46:35.877 [QUIET] [system.out]       at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
13:46:35.877 [QUIET] [system.out]       at cucumber.runtime.Runtime.run(Runtime.java:122)
13:46:35.877 [QUIET] [system.out]       at cucumber.api.cli.Main.run(Main.java:36)
13:46:35.878 [QUIET] [system.out]       at cucumber.api.cli.Main.main(Main.java:18)
13:46:35.878 [QUIET] [system.out] 
13:46:35.878 [QUIET] [system.out]       java.lang.NullPointerException
13:46:35.878 [QUIET] [system.out]               at steps.StartingSteps.tearDown(StartingSteps.java:29)
13:46:35.878 [QUIET] [system.out]               at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:46:35.878 [QUIET] [system.out]               at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:46:35.878 [QUIET] [system.out]               at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:46:35.878 [QUIET] [system.out]               at java.lang.reflect.Method.invoke(Method.java:498)
13:46:35.878 [QUIET] [system.out]               at cucumber.runtime.Utils$1.call(Utils.java:40)
13:46:35.878 [QUIET] [system.out]               at cucumber.runtime.Timeout.timeout(Timeout.java:16)
13:46:35.878 [QUIET] [system.out]               at cucumber.runtime.Utils.invoke(Utils.java:34)
13:46:35.878 [QUIET] [system.out]               at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
13:46:35.878 [QUIET] [system.out]               at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:224)
13:46:35.878 [QUIET] [system.out]               at cucumber.runtime.Runtime.runHooks(Runtime.java:212)
13:46:35.878 [QUIET] [system.out]               at cucumber.runtime.Runtime.runAfterHooks(Runtime.java:206)
13:46:35.878 [QUIET] [system.out]               at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:46)
13:46:35.878 [QUIET] [system.out]               at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
13:46:35.878 [QUIET] [system.out]               at cucumber.runtime.Runtime.run(Runtime.java:122)
13:46:35.878 [QUIET] [system.out]               at cucumber.api.cli.Main.run(Main.java:36)
13:46:35.878 [QUIET] [system.out]               at cucumber.api.cli.Main.main(Main.java:18)
13:46:35.878 [QUIET] [system.out]       
13:46:35.878 [QUIET] [system.out] 
13:46:35.878 [QUIET] [system.out]   @helloOptimus
13:46:35.878 [QUIET] [system.out]   Scenario: generic step example                                                                                                                                  # HelloOptimusGeneric.feature:6
13:46:35.878 [QUIET] [system.out]     Given optimus on Home screen verifies WelcomeMessage has textpresent value Welcome to Optimus!! You are all ready to experience Automation like never before. # GenericSteps.assertelementwithvalue(String,String,String,String,String)
13:46:35.885 [QUIET] [system.out] 
13:46:35.885 [QUIET] [system.out] Failed scenarios:
13:46:35.885 [QUIET] [system.out] HelloOptimus.feature:4 # Scenario: Hello Optimus
13:46:35.885 [QUIET] [system.out] HelloOptimusGeneric.feature:6 # Scenario: generic step example
13:46:35.885 [QUIET] [system.out] 
13:46:35.885 [QUIET] [system.out] 2 Scenarios (2 failed)
13:46:35.885 [QUIET] [system.out] 4 Steps (4 skipped)
13:46:35.886 [QUIET] [system.out] 0m5.707s
13:46:35.886 [QUIET] [system.out]

**Comment by asitishere** [comment]
Had a discussion with team and they working on it. Dependancy issue with new changes....
Will close once the code pushed and fix the report generation issue ( sent through a separate thread)

Kudos team...

**Comment by asitishere** [comment]
Hi After the new dependancy change and applying the new template changes all working as expected.

Cheers
Asit
