### ISSUE TITLE
running a bunch of test in fragmented mode (2 devices) I am facing below issue frequently but same time in console if I query adb devices in console return comes as List of devices

### ISSUE THREAD

**Issue by asitishere** [testvagrant/optimusTemplate#18]
Before StartingSteps.setUp(Scenario)

Issue: When I am running a bunch of test in fragmented mode (2 devices) I am facing below issue frequently but same time in console if I query adb devices in console return comes as List of devices. This says some how optimus failed fetch List of attached evices.
 
Any thoughts
 
Stack Trace
 
java.lang.NullPointerException: Unable to Mark Device to 'Engaged'. Check for device State using `adb devices`. If it is offline, kill the adb server `adb kill-server` and try again.
                at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:805)
                at com.testvagrant.monitor.radiator.MongoWriter.updateFirstAvailableDeviceToEngaged(MongoWriter.java:160)
                at com.testvagrant.optimus.device.DeviceFinder.getAvailableDeviceAndUpdateToEngaged(DeviceFinder.java:56)
                at com.testvagrant.optimus.parser.OptimusConfigParser.mapOwnerToDesiredCapabilities(OptimusConfigParser.java:61)
                at com.testvagrant.optimus.device.OptimusController.registerSmartBOTs(OptimusController.java:157)
                at steps.StartingSteps.setUp(StartingSteps.java:23)
                at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at cucumber.runtime.Utils$1.call(Utils.java:32)
                at cucumber.runtime.Timeout.timeout(Timeout.java:16)
                at cucumber.runtime.Utils.invoke(Utils.java:26)
                at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
                at cucumber.runtime.HookDefinitionMatch.runStep(HookDefinitionMatch.java:17)
                at cucumber.runner.UnskipableStep.executeStep(UnskipableStep.java:22)
                at cucumber.api.TestStep.run(TestStep.java:83)
                at cucumber.api.TestCase.run(TestCase.java:58)
                at cucumber.runner.Runner.runPickle(Runner.java:80)
                at cucumber.runtime.Runtime.runFeature(Runtime.java:119)
                at cucumber.runtime.Runtime.run(Runtime.java:104)
                at cucumber.api.cli.Main.run(Main.java:36)
                at cucumber.api.cli.Main.main(Main.java:18)

**Comment by sukesh15** [comment]
This was fixed in later versions. Please upgrade and try.
