### ISSUE TITLE
Issue with iOS

### ISSUE THREAD

**Issue by sampadrout** [testvagrant/optimusTemplate#4]
Here is the issue on iOS:
gradle runFragmentation -DtestFeed=HelloOptimusIOS -Dtags=@helloOptimus

> Task :compileTestJava
Note: /Users/sampadrout/AMA_New/src/test/java/pages/BasePage.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :runFragmentation
Executing MongoMain
MongoClient:1084179762
Running command ---- instruments -s devices | grep 'iPhone'
command output -- Known Devices:
Sampad’s MacBook Pro [76300B76-877E-5B6C-8A5C-63989CB37CA8]
Apple TV 1080p (10.2) [7D48EE19-760D-4044-B793-755CE912A7F6] (Simulator)
iPad (5th generation) (10.3.1) [18D78ADA-C7BC-4C49-A80B-A59BC3C7CDB1] (Simulator)
iPad 2 (8.4) [43133935-09F3-4292-B8A3-2F339552E178] (Simulator)
iPad 2 (9.0) [DD6A644E-69C0-443A-BCA4-2D7C29CF9EE5] (Simulator)
iPad 2 (9.1) [8ABC9D59-67B3-46BB-9A61-2C0AD3B5F53E] (Simulator)
iPad Air (10.3.1) [E3D79778-8161-43D2-9764-5F2DC4BF939F] (Simulator)
iPad Air (8.4) [A4737584-B9AF-4792-96D3-6024394E131F] (Simulator)
iPad Air (9.0) [3A1D59E7-FFFE-42D1-9A77-DDF340764D4F] (Simulator)
iPad Air (9.1) [D2B62DEE-8DCB-446A-B74B-423BE2690228] (Simulator)
iPad Air 2 (10.3.1) [C55DE100-1ECE-4234-9164-0AB6F944DCF3] (Simulator)
iPad Air 2 (9.0) [66714260-1523-497A-804C-E847557E0261] (Simulator)
iPad Air 2 (9.1) [79EB27CF-D24E-4ECF-A24A-A11A16DFB4ED] (Simulator)
iPad Pro (10.5-inch) (10.3.1) [E0944F65-72BB-4F78-A62F-0B6339B24EF8] (Simulator)
iPad Pro (12.9 inch) (10.3.1) [52D9DE62-8CD0-41DF-AF7C-1DF6A24D89C5] (Simulator)
iPad Pro (12.9-inch) (2nd generation) (10.3.1) [59D06F3F-EE71-4894-A877-86089101B92C] (Simulator)
iPad Pro (9.1) [7A29232E-D0CF-4354-9616-24BCDD3B37F3] (Simulator)
iPad Pro (9.7 inch) (10.3.1) [F6E358CA-6F76-45A4-B01A-9DEB8C6D6221] (Simulator)
iPad Retina (8.4) [27A0F759-1917-46BD-8092-4016BB4C352D] (Simulator)
iPad Retina (9.0) [61C74654-C198-41AD-A731-8FD8D75E61CC] (Simulator)
iPad Retina (9.1) [F9637EF8-2743-4005-992B-2FEE663F3A0C] (Simulator)
iPhone 4s (8.4) [0A2AB258-2C99-4D88-AAF3-E127B73452E1] (Simulator)
iPhone 4s (9.0) [B0D6D58B-351E-4005-A920-80B0FDD5C2F6] (Simulator)
iPhone 4s (9.1) [D3DFF92E-FD47-4B8C-833B-F40FFECEE825] (Simulator)
iPhone 5 (10.3.1) [CE24ADBE-4279-476A-97E3-78B392A0B944] (Simulator)
iPhone 5 (8.4) [6748CC2B-CA76-4669-A2E3-77DF53277E3F] (Simulator)
iPhone 5 (9.0) [77DDB9FA-BD16-409C-97D2-DED4F0DB65F4] (Simulator)
iPhone 5 (9.1) [B4DC5205-4561-4D94-8765-D20B634DE4F6] (Simulator)
iPhone 5s (10.3.1) [30D45EA2-24E2-4BEB-B557-0D6DE7FC3334] (Simulator)
iPhone 5s (8.4) [6A59986F-44BE-4043-BDD9-C364877968E3] (Simulator)
iPhone 5s (9.0) [0B356BBE-D183-42DD-843B-3B69539F074D] (Simulator)
iPhone 5s (9.1) [AE000EDB-39AE-42FE-BD3F-F511F25A351D] (Simulator)
iPhone 6 (10.3.1) [4B58CFD4-B4D1-4FBC-A2F0-A22BBC159236] (Simulator)
iPhone 6 (8.4) [9215CB23-D071-440E-B7A0-5392081F4468] (Simulator)
iPhone 6 (9.0) [ECC85B32-EB1E-4F73-AC7E-32BC972A7B7B] (Simulator)
iPhone 6 (9.1) [0587865E-62A4-4F96-A214-D043BB916FA9] (Simulator)
iPhone 6 Plus (10.3.1) [6E2F62CA-80CE-400A-BEAE-A02B83CD5D37] (Simulator)
iPhone 6 Plus (8.4) [CF141892-FBAE-4BAE-9037-C9B77A32375A] (Simulator)
iPhone 6 Plus (9.0) [355E8AA2-D4E0-4063-8D63-924605D47FC2] (Simulator)
iPhone 6 Plus (9.1) [61AE47A9-EF4F-4D31-8002-CFCC746B3DBF] (Simulator)
iPhone 6s (10.3.1) [626407FE-7E83-484C-BD98-3146B65C7D30] (Simulator)
iPhone 6s (10.3.1) + Apple Watch - 38mm (3.2) [AF13D2B4-068E-4A72-B5A6-2551E115082A] (Simulator)
iPhone 6s (9.0) [D1B66D52-586E-4476-B06A-8D1000E0133C] (Simulator)
iPhone 6s (9.1) [804D9964-3B2F-45F0-A64A-61ED51679624] (Simulator)
iPhone 6s Plus (10.3.1) [D1E354B8-A08C-4FD2-A972-AF02DE022870] (Simulator)
iPhone 6s Plus (10.3.1) + Apple Watch - 42mm (3.2) [8F7DC03E-7CD2-4DD5-B5AB-2C996C5FCAAC] (Simulator)
iPhone 6s Plus (9.0) [0D00F7DF-5117-4F54-AF83-B9E8C2DE07FB] (Simulator)
iPhone 6s Plus (9.1) [CF1826E5-1C78-4116-A6AC-A91C75F8E127] (Simulator)
iPhone 7 (10.3.1) [C5FB1A1B-7824-43B2-9636-519037095775] (Simulator)
iPhone 7 (10.3.1) + Apple Watch Series 2 - 38mm (3.2) [31DACC47-B1D8-4519-ADE3-39F0579CC803] (Simulator)
iPhone 7 Plus (10.3.1) [CD65E1F0-F797-42C3-A209-551F2548A31D] (Simulator)
iPhone 7 Plus (10.3.1) + Apple Watch Series 2 - 42mm (3.2) [1B55BB2C-2167-477B-A4F8-0312FB0D5F02] (Simulator)
iPhone SE (10.3.1) [89DBA886-5245-4895-A346-1CA1A5DB6570] (Simulator)

MongoClient:1084179762
/Users/sampadrout/AMA_New/src/test/resources/HelloOptimusIOS.json
MongoClient:1084179762

> Task :fragmentationReport
MongoClient:1084179762
MongoClient:1084179762

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':runFragmentation'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':fragmentationReport'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
==============================================================================

BUILD FAILED in 58s
7 actionable tasks: 7 executed

**Comment by KrishnB** [comment]
@sampadrout can you run the same command with `--stacktrace` and please share the output?

**Comment by sampadrout** [comment]
Here you go:
gradle runFragmentation -DtestFeed=HelloOptimusIOS -Dtags=@helloOptimus --stacktrace

> Task :compileTestJava
Note: /Users/sampadrout/AMA_New/src/test/java/pages/BasePage.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :runFragmentation
Executing MongoMain
MongoClient:2084776737
Running command ---- instruments -s devices | grep 'iPhone'
command output -- Known Devices:
Sampad’s MacBook Pro [76300B76-877E-5B6C-8A5C-63989CB37CA8]
Apple TV 1080p (10.2) [7D48EE19-760D-4044-B793-755CE912A7F6] (Simulator)
iPad (5th generation) (10.3.1) [18D78ADA-C7BC-4C49-A80B-A59BC3C7CDB1] (Simulator)
iPad 2 (8.4) [43133935-09F3-4292-B8A3-2F339552E178] (Simulator)
iPad 2 (9.0) [DD6A644E-69C0-443A-BCA4-2D7C29CF9EE5] (Simulator)
iPad 2 (9.1) [8ABC9D59-67B3-46BB-9A61-2C0AD3B5F53E] (Simulator)
iPad Air (10.3.1) [E3D79778-8161-43D2-9764-5F2DC4BF939F] (Simulator)
iPad Air (8.4) [A4737584-B9AF-4792-96D3-6024394E131F] (Simulator)
iPad Air (9.0) [3A1D59E7-FFFE-42D1-9A77-DDF340764D4F] (Simulator)
iPad Air (9.1) [D2B62DEE-8DCB-446A-B74B-423BE2690228] (Simulator)
iPad Air 2 (10.3.1) [C55DE100-1ECE-4234-9164-0AB6F944DCF3] (Simulator)
iPad Air 2 (9.0) [66714260-1523-497A-804C-E847557E0261] (Simulator)
iPad Air 2 (9.1) [79EB27CF-D24E-4ECF-A24A-A11A16DFB4ED] (Simulator)
iPad Pro (10.5-inch) (10.3.1) [E0944F65-72BB-4F78-A62F-0B6339B24EF8] (Simulator)
iPad Pro (12.9 inch) (10.3.1) [52D9DE62-8CD0-41DF-AF7C-1DF6A24D89C5] (Simulator)
iPad Pro (12.9-inch) (2nd generation) (10.3.1) [59D06F3F-EE71-4894-A877-86089101B92C] (Simulator)
iPad Pro (9.1) [7A29232E-D0CF-4354-9616-24BCDD3B37F3] (Simulator)
iPad Pro (9.7 inch) (10.3.1) [F6E358CA-6F76-45A4-B01A-9DEB8C6D6221] (Simulator)
iPad Retina (8.4) [27A0F759-1917-46BD-8092-4016BB4C352D] (Simulator)
iPad Retina (9.0) [61C74654-C198-41AD-A731-8FD8D75E61CC] (Simulator)
iPad Retina (9.1) [F9637EF8-2743-4005-992B-2FEE663F3A0C] (Simulator)
iPhone 4s (8.4) [0A2AB258-2C99-4D88-AAF3-E127B73452E1] (Simulator)
iPhone 4s (9.0) [B0D6D58B-351E-4005-A920-80B0FDD5C2F6] (Simulator)
iPhone 4s (9.1) [D3DFF92E-FD47-4B8C-833B-F40FFECEE825] (Simulator)
iPhone 5 (10.3.1) [CE24ADBE-4279-476A-97E3-78B392A0B944] (Simulator)
iPhone 5 (8.4) [6748CC2B-CA76-4669-A2E3-77DF53277E3F] (Simulator)
iPhone 5 (9.0) [77DDB9FA-BD16-409C-97D2-DED4F0DB65F4] (Simulator)
iPhone 5 (9.1) [B4DC5205-4561-4D94-8765-D20B634DE4F6] (Simulator)
iPhone 5s (10.3.1) [30D45EA2-24E2-4BEB-B557-0D6DE7FC3334] (Simulator)
iPhone 5s (8.4) [6A59986F-44BE-4043-BDD9-C364877968E3] (Simulator)
iPhone 5s (9.0) [0B356BBE-D183-42DD-843B-3B69539F074D] (Simulator)
iPhone 5s (9.1) [AE000EDB-39AE-42FE-BD3F-F511F25A351D] (Simulator)
iPhone 6 (10.3.1) [4B58CFD4-B4D1-4FBC-A2F0-A22BBC159236] (Simulator)
iPhone 6 (8.4) [9215CB23-D071-440E-B7A0-5392081F4468] (Simulator)
iPhone 6 (9.0) [ECC85B32-EB1E-4F73-AC7E-32BC972A7B7B] (Simulator)
iPhone 6 (9.1) [0587865E-62A4-4F96-A214-D043BB916FA9] (Simulator)
iPhone 6 Plus (10.3.1) [6E2F62CA-80CE-400A-BEAE-A02B83CD5D37] (Simulator)
iPhone 6 Plus (8.4) [CF141892-FBAE-4BAE-9037-C9B77A32375A] (Simulator)
iPhone 6 Plus (9.0) [355E8AA2-D4E0-4063-8D63-924605D47FC2] (Simulator)
iPhone 6 Plus (9.1) [61AE47A9-EF4F-4D31-8002-CFCC746B3DBF] (Simulator)
iPhone 6s (10.3.1) [626407FE-7E83-484C-BD98-3146B65C7D30] (Simulator)
iPhone 6s (10.3.1) + Apple Watch - 38mm (3.2) [AF13D2B4-068E-4A72-B5A6-2551E115082A] (Simulator)
iPhone 6s (9.0) [D1B66D52-586E-4476-B06A-8D1000E0133C] (Simulator)
iPhone 6s (9.1) [804D9964-3B2F-45F0-A64A-61ED51679624] (Simulator)
iPhone 6s Plus (10.3.1) [D1E354B8-A08C-4FD2-A972-AF02DE022870] (Simulator)
iPhone 6s Plus (10.3.1) + Apple Watch - 42mm (3.2) [8F7DC03E-7CD2-4DD5-B5AB-2C996C5FCAAC] (Simulator)
iPhone 6s Plus (9.0) [0D00F7DF-5117-4F54-AF83-B9E8C2DE07FB] (Simulator)
iPhone 6s Plus (9.1) [CF1826E5-1C78-4116-A6AC-A91C75F8E127] (Simulator)
iPhone 7 (10.3.1) [C5FB1A1B-7824-43B2-9636-519037095775] (Simulator)
iPhone 7 (10.3.1) + Apple Watch Series 2 - 38mm (3.2) [31DACC47-B1D8-4519-ADE3-39F0579CC803] (Simulator)
iPhone 7 Plus (10.3.1) [CD65E1F0-F797-42C3-A209-551F2548A31D] (Simulator)
iPhone 7 Plus (10.3.1) + Apple Watch Series 2 - 42mm (3.2) [1B55BB2C-2167-477B-A4F8-0312FB0D5F02] (Simulator)
iPhone SE (10.3.1) [89DBA886-5245-4895-A346-1CA1A5DB6570] (Simulator)

MongoClient:2084776737
/Users/sampadrout/AMA_New/src/test/resources/HelloOptimusIOS.json
MongoClient:2084776737

> Task :fragmentationReport
MongoClient:2084776737
MongoClient:2084776737


FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':runFragmentation'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':runFragmentation'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:242)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:235)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:224)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:121)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:77)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:102)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:96)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:612)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:567)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:96)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.NullPointerException
        at com.testvagrant.optimus.utils.Commons.lambda$getOsVerion$1(Commons.java:24)
        at com.testvagrant.optimus.utils.Commons.getOsVerion(Commons.java:24)
        at com.testvagrant.optimus.updater.DeviceMiner.lambda$getDevicesForPlatformVersion$3(DeviceMiner.java:173)
        at com.testvagrant.optimus.updater.DeviceMiner.getDevicesForPlatformVersion(DeviceMiner.java:176)
        at com.testvagrant.optimus.updater.DeviceMiner.getDevicesForPlatformVersion(DeviceMiner.java:167)
        at com.testvagrant.optimus.updater.DeviceMiner.getAllDevicesThatMatchTheCriteria(DeviceMiner.java:95)
        at com.testvagrant.optimus.helpers.DeviceHelper.getConnectedDevicesMatchingRunCriteria(DeviceHelper.java:42)
        at com.testvagrant.optimus.helpers.DeviceHelper$getConnectedDevicesMatchingRunCriteria.call(Unknown Source)
        at com.testvagrant.optimus.utils.OptimusSetup.getDevicesForThisRun(OptimusSetup.groovy:19)
        at com.testvagrant.optimus.utils.OptimusSetup$getDevicesForThisRun$0.call(Unknown Source)
        at com.testvagrant.optimus.tasks.FragmentationTask.runFragmentation(FragmentationTask.groovy:22)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:711)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:694)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 27 more

==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':fragmentationReport'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':fragmentationReport'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:242)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:235)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:224)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:121)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:77)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:102)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:96)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:612)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:567)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:96)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at com.testvagrant.optimus.parser.ReportParser.parse(ReportParser.java:54)
        at com.testvagrant.optimus.ReportMain.main(ReportMain.java:33)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.invoke(StaticMetaMethodSite.java:46)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:91)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
        at com.testvagrant.optimus.utils.OptimusTearDown.teardown(OptimusTearDown.groovy:16)
        at com.testvagrant.optimus.utils.OptimusTearDown$teardown$0.call(Unknown Source)
        at com.testvagrant.optimus.tasks.FragmentationReportTask.fragmentationReport(FragmentationReportTask.groovy:20)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:711)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:694)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 30 more

==============================================================================

BUILD FAILED in 24s
7 actionable tasks: 7 executed

**Comment by KrishnB** [comment]
@sampadrout thanks for the stacktrace. IOS 10.3.1 is currently not supported for the optimus version. We will be releasing a new version early next week. In the meanwhile, you can remove simulators with version 10.3.1 and give it a try.

**Comment by KrishnB** [comment]
@sampadrout can you please upgrade your project for below dependencies
  * optimus - 2.1.0
  * optimusgradle - 2.0

The latest version will now support IOS devices with version 10.3 and above.
