### ISSUE TITLE
Question: Elements mapping for both iOS and Android in the same project

### ISSUE THREAD

**Issue by suhasini-Ravi** [testvagrant/optimusTemplate#53]
Hi team,

In my project, the application has both iOS and Android platforms, for the same app.
Can you please let me know on how to have the elements JSON file for both iOS and android elements.

**Comment by krishnanandb-rapido** [comment]
For Optimus, the root context is app name so if your app names say app-android, and app-ios, then you can structure your elements as 
- elements
   - app-android
      - home.elements 
   - app-ios
      - home.elements

**Comment by suhasini-Ravi** [comment]
Hey Krishna,
Thank you for the reply...
I have created the below json file under resources - >elements and named it as homescreen.json

{
  "apps": [
    {
      "app": "wmt_dev.ipa",
      "elements": [
        {
          "name": "lo_payments_btn",
          "screen": "homescreen",
          "identifier": "id",
          "value": "fwo_header_label_action",
          "waitFor": "visibility"
        }
      ]
    },

    {
      "app": "wmt_dev_unhardened.apk",
      "elements": [
        {
          "name": "lo_payments_btn",
          "screen": "homescreen",
          "identifier": "id",
          "value": "i_rtl_action",
          "waitFor": "visibility"
        }
      ]
    }
  ]
}

my feature file has the line > When Iam on homescreen screen taps on lo_payments_btn

when I run the script, it is throwing the below error.

**com.testvagrant.stepdefs.exceptions.ElementsFolderNotFoundException: Cannot find elements folder for project banking-dev. Elements should be created under respective app folders.**



When Iam on homescreen screen taps on lo_payments_btn                    # GenericSteps.consumerOnScreenPerformsActionOnElement(String,String,String,String)
      com.testvagrant.stepdefs.exceptions.ElementsFolderNotFoundException: Cannot find elements folder for project banking-dev. Elements should be created under respective app folders.
        at com.testvagrant.stepdefs.finder.ElementStore.getElementsFileRelativePath(ElementStore.java:128)
        at com.testvagrant.stepdefs.finder.ElementStore.getFileName(ElementStore.java:84)
        at com.testvagrant.stepdefs.finder.ElementStore.read(ElementStore.java:36)
        at com.testvagrant.stepdefs.finder.OptimusElementFinder.getAppElement(OptimusElementFinder.java:55)
        at com.testvagrant.stepdefs.finder.OptimusElementFinder.findWebElement(OptimusElementFinder.java:39)
        at com.testvagrant.stepdefs.core.Tapster.serve(Tapster.java:84)
        at steps.GenericSteps.consumerOnScreenPerformsActionOnElement(GenericSteps.java:31)
        at ✽.Iam on homescreen screen taps on lo_payments_btn(/Order.feature:15)

**Comment by krishnanandb-rapido** [comment]
Hey, you JSON format is invalid. `app` is an invalid key in elements file. App name has to be a directory name as mentioned in the previous comment.

**Comment by krishnanandb-rapido** [comment]
Can you update the following file `/src/test/resources/META-INF/Optimus.yaml`. Default extension is `elements` please update it to `json`

**Comment by suhasini-Ravi** [comment]
Changed the belongsTo field and now getting the different error as below.

When user on OverviewPage screen tap on lo_payments_btn                           # GenericSteps.consumerOnScreenPerformsActionOnElement(String,String,String,String)
      java.lang.NullPointerException
        at com.testvagrant.stepdefs.finder.ElementStore.lambda$find$0(ElementStore.java:44)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
        at com.testvagrant.stepdefs.finder.ElementStore.find(ElementStore.java:44)
        at com.testvagrant.stepdefs.finder.OptimusElementFinder.getAppElement(OptimusElementFinder.java:55)
        at com.testvagrant.stepdefs.finder.OptimusElementFinder.findWebElement(OptimusElementFinder.java:39)
        at com.testvagrant.stepdefs.core.Tapster.serve(Tapster.java:84)
        at steps.GenericSteps.consumerOnScreenPerformsActionOnElement(GenericSteps.java:31)

**Comment by suhasini-Ravi** [comment]
Closing the issue.

Thank you again for resolving the issue
